# Generated by Django 5.1.4 on 2024-12-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_testresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-test_date']},
        ),
        migrations.AlterField(
            model_name='testresult',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, help_text='Точность', max_digits=5),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='speed',
            field=models.PositiveIntegerField(help_text='Скорость печати'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
